planning_scene_boxes:
- box_orientation_w: -0.21814324139654234
  box_orientation_x: -0.0
  box_orientation_y: 0.0
  box_orientation_z: 0.9759167619387474
  box_position_x: 74.08
  box_position_y: 76.84
  box_position_z: 0.36
  box_x_dimension: 0.8
  box_y_dimension: 0.8
  box_z_dimension: 0.72
  frame_id: map
  scene_name: table_2
- box_orientation_w: 0.5358267949789965
  box_orientation_x: 0.0
  box_orientation_y: 0.0
  box_orientation_z: 0.8443279255020151
  box_position_x: 72.15
  box_position_y: 77.66
  box_position_z: 0.3599999999999999
  box_x_dimension: 1.6
  box_y_dimension: 0.8
  box_z_dimension: 0.715
  frame_id: map
  scene_name: table_1
- box_orientation_w: -0.21814324139654234
  box_orientation_x: -0.0
  box_orientation_y: 0.0
  box_orientation_z: 0.9759167619387474
  box_position_x: 75.6
  box_position_y: 77.56
  box_position_z: 0.31999999999999984
  box_x_dimension: 1.6
  box_y_dimension: 0.8
  box_z_dimension: 0.715
  frame_id: map
  scene_name: table_3
- box_orientation_w: 1.0
  box_orientation_x: 0.0
  box_orientation_y: 0.0
  box_orientation_z: 0.0
  box_position_x: 22.7
  box_position_y: 15.04
  box_position_z: 0.36
  box_x_dimension: 0.8
  box_y_dimension: 0.8
  box_z_dimension: 0.72
  frame_id: map
  scene_name: table_4
- box_orientation_w: -0.21814324139654234
  box_orientation_x: -0.0
  box_orientation_y: 0.0
  box_orientation_z: 0.9759167619387474
  box_position_x: 73.57
  box_position_y: 79.8
  box_position_z: 1.1999999999999993
  box_x_dimension: 5.3
  box_y_dimension: 0.48
  box_z_dimension: 2.34
  frame_id: map
  scene_name: back_wall
- box_orientation_w: -0.21814324139654234
  box_orientation_x: -0.0
  box_orientation_y: 0.0
  box_orientation_z: 0.9759167619387474
  box_position_x: 74.48
  box_position_y: 78.27
  box_position_z: 2.1999999999999993
  box_x_dimension: 5.4
  box_y_dimension: 2.9
  box_z_dimension: 0.1
  frame_id: map
  scene_name: roof
