# a list of boxes to add to the planning scene
#
# map
# +----> y        +-------+
# |               |       |
# |               |       |
# v               |       |
# x               |table_3|
#                 |       |
#                 |       |
#                 |       |
#                 +-------+
#
#                 +-------+
#                 |       |
#                 |       |
#                 |       |
#                 |table_2|
#                 |       |
#                 |       |
#                 |       |
#                 +-------+
# +--------------+
# |              |
# |    table_1   |
# |              |
# +--------------+

planning_scene_boxes:
  - scene_name: 'table_1'
    frame_id: 'map'
    box_x_dimension: 1.40
    box_y_dimension: 0.70
    box_z_dimension: 0.72
    box_position_x: 13.22
    box_position_y: 2.15
    box_position_z: 0.36
    box_orientation_x: 0.0
    box_orientation_y: 0.0
    box_orientation_z: 0.7071
    box_orientation_w: 0.7071
  - scene_name: 'table_2'
    frame_id: 'map'
    box_x_dimension: 1.40
    box_y_dimension: 0.70
    box_z_dimension: 0.72
    box_position_x: 12.07
    box_position_y: 3.35
    box_position_z: 0.36
    box_orientation_x: 0.0
    box_orientation_y: 0.0
    box_orientation_z: 0.06279051952931337
    box_orientation_w: 0.9980267284282716
  - scene_name: 'table_3'
    frame_id: 'map'
    box_x_dimension: 1.40
    box_y_dimension: 0.70
    box_z_dimension: 0.72
    box_position_x: 10.42
    box_position_y: 3.25
    box_position_z: 0.36
    box_orientation_x: 0.0
    box_orientation_y: 0.0
    box_orientation_z: 1.0
    box_orientation_w: 0.0
  - scene_name: 'back_wall_1'
    frame_id: 'map'
    box_x_dimension: 3.1
    box_y_dimension: 0.2
    box_z_dimension: 2.0
    box_position_x: 10.65
    box_position_y: 1.15
    box_position_z: 1.0
    box_orientation_x: 0.0
    box_orientation_y: 0.0
    box_orientation_z: 0.0
    box_orientation_w: 1.0
  - scene_name: 'back_wall_2'
    frame_id: 'map'
    box_x_dimension: 1.4
    box_y_dimension: 0.25
    box_z_dimension: 2.0
    box_position_x: 12.85
    box_position_y: 1.38
    box_position_z: 1.0
    box_orientation_x: 0.0
    box_orientation_y: 0.0
    box_orientation_z: 0.0
    box_orientation_w: 1.0
  - scene_name: 'side_wall_1'
    frame_id: 'map'
    box_x_dimension: 0.2
    box_y_dimension: 1.8
    box_z_dimension: 2.0
    box_position_x: 9.2
    box_position_y: 2.15
    box_position_z: 1.0
    box_orientation_x: 0.0
    box_orientation_y: 0.0
    box_orientation_z: 0.0
    box_orientation_w: 1.0
  - scene_name: 'side_wall_2'
    frame_id: 'map'
    box_x_dimension: 0.28
    box_y_dimension: 0.63
    box_z_dimension: 2.0
    box_position_x: 9.45
    box_position_y: 3.28
    box_position_z: 1.0
    box_orientation_x: 0.0
    box_orientation_y: 0.0
    box_orientation_z: 0.0
    box_orientation_w: 1.0
