# a list of boxes to add to the planning scene
#
# map
# +----> y
# |
# |
# v
# x
#
#                 +--------------+
#                 |              |
#                 | parts_table  |
#                 |              |
#                 +--------------+
#
#
#
#
#
#
#
#                 +--------------+
#                 |              |
#                 |assembly_table|
#                 |              |
#                 +--------------+
#

planning_scene_boxes:
  - scene_name: 'parts_table'
    frame_id: 'map'
    box_x_dimension: 0.7
    box_y_dimension: 1.4
    box_z_dimension: 0.72
    box_position_x: 19.735
    box_position_y: 15.37
    box_position_z: 0.36
    box_orientation_x: 0.0
    box_orientation_y: 0.0
    box_orientation_z: 0.00499998
    box_orientation_w: 0.9999875
  - scene_name: 'assembly_table'
    frame_id: 'map'
    box_x_dimension: 0.7
    box_y_dimension: 1.4
    box_z_dimension: 0.72
    box_position_x: 23.22
    box_position_y: 15.37
    box_position_z: 0.36
    box_orientation_x: 0.0
    box_orientation_y: 0.0
    box_orientation_z: 0.00499998
    box_orientation_w: 0.9999875
  - scene_name: 'side_wall'
    frame_id: 'map'
    box_x_dimension: 7.0
    box_y_dimension: 0.6
    box_z_dimension: 2.0
    box_position_x: 19.5
    box_position_y: 16.45
    box_position_z: 1.0
    box_orientation_x: 0.0
    box_orientation_y: 0.0
    box_orientation_z: 0.00399999
    box_orientation_w: 0.999992
