name: Build and run ROS tests
on: [push, pull_request]

# avoid keyboard configuration dialog
env:
  DEBIAN_FRONTEND: 'noninteractive'

jobs:
  build:
    strategy:
      matrix:
        rosdistro: [noetic]
    runs-on: ubuntu-latest
    container:
      image: ros:${{ matrix.rosdistro }}-ros-core
    steps:
    - name: Install apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang-format-10 file git python3-catkin-lint python3-catkin-tools python3-pip python3-rosdep shellcheck
    - name: Install pip dependencies
      run: pip install pre-commit
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        path: src/mobipick_labs
    - name: Run install-deps.sh
      run: |
        src/mobipick_labs/install-deps.sh
    - name: Build
      run: |
        . /opt/ros/${{ matrix.rosdistro }}/setup.sh
        catkin init
        catkin config -j 1 -p 1
        catkin config --extend /opt/ros/noetic
        catkin config --merge-devel # workaround for https://github.com/catkin/catkin_tools/issues/376
        catkin build --limit-status-rate 0.1 --no-notify
    - name: Run tests
      run: |
        . devel/setup.sh
        catkin run_tests rqt_tables_demo tables_demo_bringup tables_demo_planning
        catkin_test_results
    - name: Run pre-commit hooks
      run: |
        . devel/setup.sh
        cd src/mobipick_labs
        pre-commit run -a
